# Change these first
owner: FTRPRF # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CodeFever
    url: https://www.codefever.be
  - name: FTRPRF
    url: https://www.ftrprf.be
  - name: CodeCosmos
    url: https://www.codecosmos.com
  - name: CodeFever APP
    url: https://app.codefever.be

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.ftrprf.be
  # baseUrl: /upptime
  logoUrl: https://ftrprf.be/wp-content/uploads/2022/11/Middel-9.png
  name: FTRPRF
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
